language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database formoms;' -U postgres

script:
  - cd formoms
  - python manage.py test
  
# after_success:
#   - coveralls