language: python

python:
  - "3.6"

install:
  - pip install -r requirements-build.txt

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database formoms;' -U postgres

script:
  - cd formoms
  - python manage.py test
  
# after_success:
#   - coveralls