anguage: python
python:
  - "3.6"
env:
  - CC_TEST_REPORTER_ID=e57a22b35edfb81a9ce33540af45efd1cb9ee44db2a020caa06f4477cf47dc82 
# command to install dependencies
install:
  - pip install -r requirements.txt
  anguage: python
python:
  - "3.6"
env:
  - CC_TEST_REPORTER_ID=e57a22b35edfb81a9ce33540af45efd1cb9ee44db2a020caa06f4477cf47dc82 

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - find ./authors/ -name \*.py -exec flake8 -v {} +

# command to run tests
script: 
  - python manage.py makemigrations --settings=authors.settings.test
  - python manage.py migrate --settings=authors.settings.test 
  - coverage run --source=authors.apps ./manage.py test --settings=authors.settings.test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - find ./authors/ -name \*.py -exec flake8 -v {} +

# command to run tests
script: 
  - python manage.py makemigrations --settings=authors.settings.test
  - python manage.py migrate --settings=authors.settings.test 
  - coverage run --source=authors.apps ./manage.py test --settings=authors.settings.test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  