language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - python manage.py makemigrations --settings=formoms.settings.test
  - python manage.py migrate --settings=formoms.settings.test 
  