language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

addons:
  postgresql: "9.4"

script:
  - cd formoms
  - coverage run --source=formoms manage.py test

after_success:
  - coveralls
